<?php

return [
    'business_partners' => [
        [
            'external_bp_code' => 'SAP-DMY-0001',
            'name' => 'Toko Dummy Sudirman',
            'address' => 'Jl. Jenderal Sudirman Kav. 10, Jakarta Pusat',
            'branch' => 'Jakarta Pusat',
            'area' => 'Jakarta Pusat',
            'city' => 'Jakarta',
            'status' => 'active',
            'geofence_radius' => 50,
            'is_priority' => true,
            'tags' => ['dummy', 'sap', 'central-jakarta'],
            'latitude' => null,
            'longitude' => null,
        ],
        [
            'external_bp_code' => 'SAP-DMY-0002',
            'name' => 'Toko Dummy Thamrin',
            'address' => 'Jl. M.H. Thamrin No. 15, Jakarta Pusat',
            'branch' => 'Jakarta Pusat',
            'area' => 'Jakarta Pusat',
            'city' => 'Jakarta',
            'status' => 'active',
            'geofence_radius' => 50,
            'is_priority' => false,
            'tags' => ['dummy', 'sap', 'central-jakarta'],
            'latitude' => null,
            'longitude' => null,
        ],
        [
            'external_bp_code' => 'SAP-DMY-0003',
            'name' => 'Toko Dummy Kuningan',
            'address' => 'Jl. HR Rasuna Said, Jakarta Selatan',
            'branch' => 'Jakarta Selatan',
            'area' => 'Jakarta Selatan',
            'city' => 'Jakarta',
            'status' => 'active',
            'geofence_radius' => 50,
            'is_priority' => true,
            'tags' => ['dummy', 'sap', 'south-jakarta'],
            'latitude' => null,
            'longitude' => null,
        ],
        [
            'external_bp_code' => 'SAP-DMY-0004',
            'name' => 'Toko Dummy Kelapa Gading',
            'address' => 'Jl. Boulevard Raya, Jakarta Utara',
            'branch' => 'Jakarta Utara',
            'area' => 'Jakarta Utara',
            'city' => 'Jakarta',
            'status' => 'active',
            'geofence_radius' => 50,
            'is_priority' => false,
            'tags' => ['dummy', 'sap', 'north-jakarta'],
            'latitude' => null,
            'longitude' => null,
        ],
        [
            'external_bp_code' => 'SAP-DMY-0005',
            'name' => 'Toko Dummy BSD',
            'address' => 'Jl. BSD Raya Utama, Tangerang Selatan',
            'branch' => 'Tangerang Selatan',
            'area' => 'Tangerang Selatan',
            'city' => 'Tangerang Selatan',
            'status' => 'active',
            'geofence_radius' => 50,
            'is_priority' => false,
            'tags' => ['dummy', 'sap', 'tangerang-selatan'],
            'latitude' => null,
            'longitude' => null,
        ],
    ],
];
